#!/bin/bash -e
cd "$(git rev-parse --show-toplevel)"

[[ $FORK ]] || FORK='https://github.com/amerlyq'

creds(){ ! hash 'r.git-my-repo' &>/dev/null || (cd "$1" && r.git-my-repo); }
clone(){ if [[ ! -d $2 ]]; then mkdir -p "$2"; git clone "$@"; fi; creds "$2"; }

creds "$PWD"

clone "$FORK/aeternum-cmake-cross" cmake/cross
clone "$FORK/aeternum-jekyll-offline" jekyll/offline
