#!/usr/bin/env bash
#%SUMMARY: print built-in rules and variables
#%USAGE: $ ./$0 [-rR --warn-undefined-variables] [--] [some] V +'setf make'
set -euo pipefail
exec 2> /dev/null
! env --ignore-environment -- make --file "/dev/null" --print-data-base "$@"
