#!/bin/bash -eu
source ~/.shell/func.d/packages
# PERF:(17.2MB) OpenGL Graphics

pkg_inst glfw-x11

exit 1

LST="$LST freeglut3 freeglut3-dev"
LST="$LST glew-utils glew1.5-dev libglew-dev libglew1.5-dev libglm-dev"
LST="$LST mesa-utils mesa-common-dev mesa-vdpau-drivers libgl1-mesa-dev libglu1-mesa-dev"
LST="$LST libxrandr-dev x11proto-randr-dev libx11-dev libxi-dev"

if distro arch; then
  pkg_inst $LST

elif distro ubuntu; then
  pkg_inst $LST
fi
