#%SUMMARY: cwd must be in same dir
#%USAGE: $ make [args] [--] [tgts]
#%SEE:(possible searched names): strace -e trace=%file make
#%
#%REF:(packaging conventions): https://www.gnu.org/prep/standards/html_node/Makefile-Conventions.html
#% * [standard targets]: https://www.gnu.org/prep/standards/html_node/Standard-Targets.html
#% * [standard vars]: https://www.gnu.org/prep/standards/html_node/Directory-Variables.html
#%
all:
	echo hi
