#!/usr/bin/env bash

# http://www.cyberciti.biz/faq/bash-for-loop/

for line in $(Linux-Or-Unix-Command-Here); do echo $line; done
for i in 1 2 3 4 5; do echo $i; done
for i in {1..5}; do echo $i; done     #3.0+
for i in {0..10..2}; do echo $i; done #4.0+
for i in "${arrayName[@]}"; do echo $i; done
for ((i=0; i<${#a[@]}; ++i)); do echo "$i" "${a[i]}"; done
