#!/usr/bin/env bash
exit

# '-' -- last EOT can be indented with hardtabs
# first 'EOT' in single quotes -- then bash don't expands vars inside heredoc

# As concrete file
echo "text" | gawk -f <(cat - <<-'EOT'
    BEGIN{ }
    { print $0 }
EOT
) | grep "ex"

# As stdin input
sed '/cho/!d' << EOT | grep "ex"
choosen table exec
another entry
EOT

# W/o subsheel (or use '(...)')
{ cat <<EOF
touch /tmp/somefile
echo foo > /tmp/somefile
EOF
} | sh


# Weird order
cat <<EOF |
touch /tmp/somefile
echo foo > /tmp/somefile
EOF
sh

# Direct piping
sh >/tmp/out << EOT
touch /tmp/somefile
echo foo > /tmp/somefile
EOT

# Several together
( cat; echo ---; cat <&3 ) <<EOF 3<<EOF2
hi
EOF
there
EOF2
