#!/usr/bin/cmake -P

message(" *** DEBUG search paths

 0) CMAKE_STAGING_PREFIX=${CMAKE_STAGING_PREFIX}
      = always abspath on host without prefix
    CMAKE_FIND_ROOT_PATH=${CMAKE_FIND_ROOT_PATH}
      = prepend to all other dirs beside staging
    CMAKE_FIND_ROOT_PATH_MODE_LIBRARY=${CMAKE_FIND_ROOT_PATH_MODE_LIBRARY}
    CMAKE_SYSROOT=${CMAKE_SYSROOT}
      = single dir to use as prefix

 1) CMAKE_PREFIX_PATH=${CMAKE_PREFIX_PATH}
    CMAKE_LIBRARY_PATH=${CMAKE_LIBRARY_PATH}
    CMAKE_LIBRARY_ARCHITECTURE=${CMAKE_LIBRARY_ARCHITECTURE}
    CMAKE_FRAMEWORK_PATH=${CMAKE_FRAMEWORK_PATH}

 2) env vars with same names
 3) ... HINTS
 4) system env vars e.g. LIB=$ENV{LIB}

 5) CMAKE_SYSTEM_PREFIX_PATH=${CMAKE_SYSTEM_PREFIX_PATH}
      = includes:
      CMAKE_INSTALL_PREFIX=${CMAKE_INSTALL_PREFIX}
      CMAKE_FIND_NO_INSTALL_PREFIX=${CMAKE_FIND_NO_INSTALL_PREFIX}
    CMAKE_SYSTEM_LIBRARY_PATH=${CMAKE_SYSTEM_LIBRARY_PATH}
    CMAKE_SYSTEM_FRAMEWORK_PATH=${CMAKE_SYSTEM_FRAMEWORK_PATH}

 6) ... PATHS
")
